//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Search {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SearchSource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SearchSource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Search.SearchSource", typeof(SearchSource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When did you last go out and run.. couple miles? Yes now.. in February when nature is starting to refresh. .
        /// </summary>
        public static string Content1 {
            get {
                return ResourceManager.GetString("Content1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It’s early June in Cincinnati and the city is steamy after a recent rain. Elderly women fan themselves at bus stops. Tattooed tweakers panhandle in Fountain Square. Men in sweat-stained oxford shirts line up for lunch at Skyline Chili. Downtown is threadbare and lightly populated — everyone is either in their temperature-controlled offices or sitting in their cars, windows up, AC blasting, immune to the outside world.
        ///
        ///Like many Midwestern cities, Cincinnati&apos;s public transit system has seen better times.  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content10 {
            get {
                return ResourceManager.GetString("Content10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may wonder what have this 2 words in common? Nothing at first look. But snow is protecting the green when Santa Claus is comming from beer. Yes in March.. he is partying all year :D.
        /// </summary>
        public static string Content2 {
            get {
                return ResourceManager.GetString("Content2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andy Baio recruited some of the web’s most fascinating creators to the Portland festival he runs with Andy McMillan, and the result is new attention for some criminally under-viewed projects.
        ///
        ///Nearly everything I saw this year was something I wanted to share with a friend — you can check out the entire lineup here. Below are some of my very favorite things, any one which would happily occupy a weekend afternoon..
        /// </summary>
        public static string Content3 {
            get {
                return ResourceManager.GetString("Content3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;No one expects the lady code troll&quot; — thus began Jenn Schiffer’s rollicking presentation about her series of Medium satires, which make absurd arguments about software development that bait men — and it is almost always men — into rageful fits of mansplaining. The essays are hilarious, and the responses are often sublime — although they also illustrate the toxic masculinity of many coding subcultures, as Schiffer noted in her talk’s powerful conclusion..
        /// </summary>
        public static string Content4 {
            get {
                return ResourceManager.GetString("Content4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rollout of bots by companies including Facebook and Google this year has generally been underwhelming. But while tech giants work to determine how AI can become the next multibillion-dollar industry, a host of hackers are working to create Twitter bots that are absurdist, artsy, and beautiful..
        /// </summary>
        public static string Content5 {
            get {
                return ResourceManager.GetString("Content5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The introduction of bots to Facebook and other platforms has been overhyped — and the bots themselves often aren&apos;t very good, Facebook Messenger chief David Marcus said today. Speaking at the TechCrunch Disrupt conference in San Francisco, Marcus made some of his first public comments about bots since Facebook launched the platform in April. &quot;It got really overhyped really, really quickly,&quot; Marcus said. What&apos;s more, he said, many of the first bots to hit the platform weren&apos;t nearly as good as the native app [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content6 {
            get {
                return ResourceManager.GetString("Content6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcus acknowledged that the two weeks Facebook gave developers to build bots before its F8 developer conference this year was &quot;probably not&quot; enough time for them to create great experiences. But he said he was satisfied with their progress to date. &quot;This is a long journey, and you have to start somewhere,&quot; he said.
        ///
        ///Marcus made his comments during a talk in which he also announced to an update to the bot platform which lets users pay bots using credit card information stored with Facebook for the first t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content7 {
            get {
                return ResourceManager.GetString("Content7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram started allowing certain high-profile users to filter specific words out of their comments section earlier this summer, and today, the company is rolling that feature out to everyone.
        ///
        ///Users can specify which custom words they want hidden from their comments and also turn on the &quot;hide inappropriate comments&quot; feature, which hides comments containing words that are typically flagged as inappropriate. This can all be accessed by clicking the gear icon. Instagram is also updating the way it displays [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content8 {
            get {
                return ResourceManager.GetString("Content8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A philanthropist asked a racecar designer to make an all-terrain vehicle suitable for humanitarian missions in Africa. The result was the Ox, “the world’s first flatpack truck” — meaning it can be packed up into a flat box and shipped like Ikea furniture.
        ///
        ///The truck is absurdly simple to assemble: its designers claim that three people can break it down into 60 parts in just 12 hours. (Apparently no one involved with the truck&apos;s creation has ever tried to put together the Liatorp.) This allows the Ox to be [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content9 {
            get {
                return ResourceManager.GetString("Content9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring is knocking.
        /// </summary>
        public static string Name1 {
            get {
                return ResourceManager.GetString("Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRAIN TO NOWHERE.
        /// </summary>
        public static string Name10 {
            get {
                return ResourceManager.GetString("Name10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green and Snow.
        /// </summary>
        public static string Name2 {
            get {
                return ResourceManager.GetString("Name2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our favorite discoveries from the internet&apos;s best festival.
        /// </summary>
        public static string Name3 {
            get {
                return ResourceManager.GetString("Name3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO ONE EXPECTS THE LADY CODE TROLL.
        /// </summary>
        public static string Name4 {
            get {
                return ResourceManager.GetString("Name4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bots.
        /// </summary>
        public static string Name5 {
            get {
                return ResourceManager.GetString("Name5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bots are overhyped and underpowered.
        /// </summary>
        public static string Name6 {
            get {
                return ResourceManager.GetString("Name6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOTS SUFFER FROM A PERCEPTION THAT THEY ARE NOT AS USEFUL AS ADVERTISED.
        /// </summary>
        public static string Name7 {
            get {
                return ResourceManager.GetString("Name7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram is now letting everyone filter abusive words out of their comments.
        /// </summary>
        public static string Name8 {
            get {
                return ResourceManager.GetString("Name8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet the world&apos;s first vehicle that can be packed up and shipped like Ikea furniture.
        /// </summary>
        public static string Name9 {
            get {
                return ResourceManager.GetString("Name9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blog.
        /// </summary>
        public static string Type1 {
            get {
                return ResourceManager.GetString("Type1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cod.
        /// </summary>
        public static string Type10 {
            get {
                return ResourceManager.GetString("Type10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blog.
        /// </summary>
        public static string Type2 {
            get {
                return ResourceManager.GetString("Type2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blog.
        /// </summary>
        public static string Type3 {
            get {
                return ResourceManager.GetString("Type3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blog.
        /// </summary>
        public static string Type4 {
            get {
                return ResourceManager.GetString("Type4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cod.
        /// </summary>
        public static string Type5 {
            get {
                return ResourceManager.GetString("Type5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cod.
        /// </summary>
        public static string Type6 {
            get {
                return ResourceManager.GetString("Type6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cod.
        /// </summary>
        public static string Type7 {
            get {
                return ResourceManager.GetString("Type7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cod.
        /// </summary>
        public static string Type8 {
            get {
                return ResourceManager.GetString("Type8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cod.
        /// </summary>
        public static string Type9 {
            get {
                return ResourceManager.GetString("Type9", resourceCulture);
            }
        }
    }
}
